{% set name = "coloredlogs" %}
{% set version = "14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coloredlogs-{{ version }}.tar.gz
  sha256: a1fab193d2053aa6c0a97608c4342d031f1f93a3d1218432c59322441d31a505

build:
  number: 3
  noarch: python
  entry_points:
    - coloredlogs = coloredlogs.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - humanfriendly >=7.1

test:
  imports:
    - coloredlogs
    - coloredlogs.converter
  commands:
    - pip check
    - coloredlogs --help
  requires:
    - pip

about:
  home: https://coloredlogs.readthedocs.io
  summary: Colored terminal output for Python's logging module
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - andfoy
    - ccordoba12
