{% set version = "11.0" %}

package:
  name: coloredlogs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
  sha256: e2491675507a2e4048bf3b4c5ce4ee55354c8d659a58d9c946da05ca3e6a2f5b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - coloredlogs = coloredlogs.cli:main

requirements:
  build:
    - python
    - pip
    - humanfriendly >=4.7
  run:
    - python
    - humanfriendly >=4.7
    - colorama  # [win]

test:
  imports:
    - coloredlogs
# Probably requires a valid TERM and a pager, it is hanging on our CIs.
#  commands:
#    - coloredlogs --help  # [not osx]

about:
  home: https://coloredlogs.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Colored terminal output for Python's logging module

extra:
  recipe-maintainers:
    - ocefpaf
    - andfoy
    - ccordoba12
