{% set version = "14.2" %}

package:
  name: coloredlogs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
  sha256: ac35144b5c39699318fdea8afdf3ca3308f274759af56a479e6d657b1850e246

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - coloredlogs = coloredlogs.cli:main

requirements:
  host:
    - python
    - pip
    - humanfriendly >=7.1
  run:
    - python
    - humanfriendly >=7.1

test:
  imports:
    - coloredlogs
# Probably requires a valid TERM and a pager, it is hanging on our CIs.
#  commands:
#    - coloredlogs --help  # [not osx]

about:
  home: https://coloredlogs.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Colored terminal output for Python's logging module

extra:
  recipe-maintainers:
    - ocefpaf
    - andfoy
    - ccordoba12
